name: python CI 

on: 
  push: 
    branches: [ "main" ]

jobs: 

    build: 
      runs-on: ubuntu-latest 

      steps: 
      - uses: actions/checkout@v3
      - name: Setup python 3.10 
        uses: actions/setup-python@v3
      - run: pip install -r requirements.txt
      - run: python test_main.py
    deploy: 
        name: deploy 
        needs: [build] 
        runs-on: ubuntu-latest 
        steps: 
          - name: Deploy to production
            uses: johnbeynon/render-deploy-action@v0.0.8
            with: 
              service-id: ${{ secrets.SECRET_ID }}
              api-key: ${{ secrets.SECRET_KEY }}
          - name: Mensaje de Discord
            uses: sarisia/actions-status-discord@v1
            if: failure()
            with:
              webhook: ${{ secrets.SECFRETS_WEBHOOK }}
              title: "test"
              description: "El test fallo"
              message: "Error en el test"
                

      